### ISSUE TITLE
Can you update your example with latest version of the launch darkly flutter plugin

### ISSUE THREAD

**Issue by SatishKumarRaizada** [launchdarkly/hello-flutter#6]
The current latest version of the Flutter Launch Darkly FLutter SDK is ```launchdarkly_flutter_client_sdk: ^3.0.1``` but the example contains much older version.

There are configuration changes in latest version of the launchdarkly SDK.

**Comment by tanderson-ld** [comment]
@SatishKumarRaizada, thank you for bringing this to our attention.  Were you able to figure out the necessary configuration changes?

**Comment by SatishKumarRaizada** [comment]
@tanderson-ld Yes i managed to configure and use it. Would it make sense to add examples for each of the flag types specially the flag which gives back json objects, i am trying to find the documentation on how to read json on the client. I would appreciate if you can guide me here with some examples!!

Example, how to obtain this flag value JSON -
```
{
  "action": {
    "nameDisplay": true,
    "email": "myemail@gmail.com",
  },
  "detail": {
    "name": "My Name",
    "roleAssigned": true,
  },
  "fallback": {
    "nameDisplay": true,
    "email": "notmyemail@gmail.com",
  }
}

```
Thank you for prompt response!!

**Comment by SatishKumarRaizada** [comment]
Yes, got it fixed. There is catch in the launch darkly dashboard when an flag is created. You manually need to tell if you are going to use this for `SDKs using Mobile key` and `SDKs using Client-side ID` and check these fields to make them working for respected platforms.

Which is overkill, perhaps this can be covered in the documentation.
